### ISSUE TITLE
Highlighting of words with hyphens

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/gp-finder#115] opened 2017-05-22 08:30 UTC
See this search for 'stockton' (e.g. https://beta.nhs.uk/book-a-gp-appointment/results?search=stockton).

The search finds matches in 'Stockton-On-Tees' but highlighting is not applied.  

![screen shot 2017-05-22 at 09 27 38](https://cloud.githubusercontent.com/assets/212582/26298953/f87f3636-3ed0-11e7-9b83-1be910428e06.png)

**Comment by st3v3nhunt** [comment] 2017-05-22 08:46
Duplicate of #116 I think? Reckon it can be closed @neilbmclaughlin ?

**Closed** 2017-05-24 11:52 UTC
